export default [
    "",
    {
        title: "知识碎片",
        collapsable: false,
        children: [
            "性能优化.md",
            "存储优化.md",
            "Spring-Validation注解实现校验.md",
            "FreeMarker模板引擎.md",
            "复制文件.md",
            "Java命令行开发.md",
            "对象存储使用.md",
            "自定义Starter.md",
            "支付宝沙箱.md",
            "简单Java爬虫.md",
            "RabbitMq配置及使用.md",
            "SpringBoot发送简单邮件.md",
            "SpringBoot结合七牛云.md",
            "XXL-JOB简单实战.md",
            "前端记住密码功能.md",
            '路由守卫.md',
            "wangEditor实现图片上传.md",
            "微信小程序模板消息.md",
            "SpringBoot自定义实现日志记录.md",
            "复制List对象.md",
            "MP的getOne查询出多条数据.md",
            "Avue实现表格指定行样式.md",
            "Uniapp小程序转换为h5网页请求后端.md",
            "多数据源使用事物失效.md",
            "Mysql的EXTRACT函数.md",
            "Vertx监听指定端口.md",
            "自定义序列化和反序列化.md"
        ],
    },
];
